"""add profile_ready_for_search flag

Revision ID: 39dcd2188b85
Revises: 5d0b33d7c312
Create Date: 2026-06-16 14:46:21.524603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39dcd2188b85'
down_revision: Union[str, Sequence[str], None] = '5d0b33d7c312'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_ready_for_search', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_ready_for_search')
    # ### end Alembic commands ###
