"""add dedup fields to seen_vacancies

Revision ID: 5d0b33d7c312
Revises: cd59e2dfe9d1
Create Date: 2026-06-15 18:29:09.813328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d0b33d7c312'
down_revision: Union[str, Sequence[str], None] = 'cd59e2dfe9d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seen_vacancies', sa.Column('content_fingerprint', sa.String(length=64), nullable=True))
    op.add_column('seen_vacancies', sa.Column('global_external_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_seen_vacancies_content_fingerprint'), 'seen_vacancies', ['content_fingerprint'], unique=False)
    op.create_index(op.f('ix_seen_vacancies_global_external_id'), 'seen_vacancies', ['global_external_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_seen_vacancies_global_external_id'), table_name='seen_vacancies')
    op.drop_index(op.f('ix_seen_vacancies_content_fingerprint'), table_name='seen_vacancies')
    op.drop_column('seen_vacancies', 'global_external_id')
    op.drop_column('seen_vacancies', 'content_fingerprint')
    # ### end Alembic commands ###
